spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    #consumer:
      #enable-auto-commit: true
      #bootstrap-servers: localhost:9092
      #group-id: my_consumer_group
      #auto-offset-reset: earliest
      #key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      #value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      #properties:
        #spring:
          #json:
            #trusted:
              #packages: '*'
        #spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        #spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
